# site settings
title: Spark Tsang
email: cashtsang@gmail.com
description: My Life, My Philosophy, My works
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sparktsang.github.io" # the base hostname & protocol for your site
author: Spark Tsang

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/sparktsang
  Facebook: https://www.facebook.com/spark.cs.tsang

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
