# site settings
title: Spark Tsang
email: cashtsang@gmail.com
description: My Life is the evidence. My Philosophy is the law. My Works are the world to come.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sparktsang.github.io" # the base hostname & protocol for your site
author: Spark Tsang
future: true

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  envelope: mailto:cashtsang@gmail.com
  Facebook: https://www.facebook.com/spark.cs.tsang
  WhatsApp: https://wa.me/85260814453
  telegram: https://t.me/Glorydeep

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
